### ISSUE TITLE
[3.0.2] broken and unusable sources

### ISSUE THREAD

**Issue by remicollet** [ip2location/ip2proxy-pecl#4]
In bc6fe6aaf47ac6ff1b5634b89a2d7e972b2a002e the ip2proxy.c file is no more the PHP extension one, everything is missing.

**Comment by remicollet** [comment]
`Warning: PHP Startup: Invalid library (maybe not a PHP library) 'modules/ip2proxy.so' in Unknown on line 0`

**Comment by ip2location-com** [comment]
The ip2proxy.c was mistakenly overwritten by the C library. Got it fixed now.
